### ISSUE TITLE
No xlsx support

### ISSUE THREAD

**Issue by lavakalas** [twz915/excel#1]
```
Traceback (most recent call last):
  File "C:\Users\lavakalas\PycharmProjects\MedSchedule\workshop.py", line 5, in <module>
    f = OpenExcel('file.xlsx')
  File "C:\Users\lavakalas\PycharmProjects\MedSchedule\venv\lib\site-packages\excel\xlrd_shortcuts.py", line 40, in __init__
    self.data = open_workbook(path)
  File "C:\Users\lavakalas\PycharmProjects\MedSchedule\venv\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
```

**Comment by twz915** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/
see https://openpyxl.readthedocs.io/en/stable/usage.html#read-an-existing-workbook
```python
>>> from openpyxl import load_workbook
>>> wb = load_workbook(filename = 'empty_book.xlsx')
>>> sheet_ranges = wb['range names']
>>> print(sheet_ranges['D18'].value)
3
```

**Comment by lavakalas** [comment]
helped a lot, thanks a lot)
